export { default as NotFound } from './not-found/NotFound'
export { default as Header } from './header/Header'
export { default as SubHeader } from './sub-header/SubHeader'
export { default as SubFooter } from './sub-footer/SubFooter'
export { default as Footer } from './footer/Footer'
export { default as Loading } from './loading/Loading'
export { default as PageTitle } from './page-title/PageTitle'
